extends Node

var CURRENT_SCENE = "world"

var PLAYER_HEALTH = 100
var PLAYER_SPEED = 45

var PLAYER_IS_ATTACKING = false
var PLAYER_CURRENT_DIRECTION = "down"

var PLAYER_ON_SCENE_TRIGGER = false

var CAVE_CHEST_KEY_TAKEN = false
